name: singularity-rstudio-nvim
#################################
# This workflow builds a Singularity container from a Singularity definition file
# and releases it as a GitHub release asset
# Reference:
# - https://github.com/singularityhub/github-ci/blob/master/.github/workflows/native-install.yml
#################################
on:
  push:
    tags:
      - 'rstudio-nvim'
    paths:
      - singularity-def/rstudio-nvim.def
  # pull_request:
  #   paths:
  #     - singularity-def/rstudio-nvim.def
jobs:
  build-singularity:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go 1.23.4
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential libc6 libfuse2 libglib2.0-0 \
            libseccomp2 zlib1g crun cryptsetup-bin fuse \
            fuse2fs squashfs-tools uidmap
      
      - name: Install Singularity
        run: |
          wget -nv -O /tmp/singularity.deb  https://github.com/sylabs/singularity/releases/download/v4.2.2/singularity-ce_4.2.2-jammy_amd64.deb
          sudo dpkg -i /tmp/singularity.deb
          rm /tmp/singularity.deb
    
      - name: Build Singularity Container
        run: |
          sudo singularity build rstudio-nvim.sif singularity-def/rstudio-nvim.def
    
      - name: Release Singularity Container
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: rstudio-nvim.sif,singularity-def/rstudio-nvim.def
